name: 'Run the tests in all wagons with a specific core revision'

on:
  workflow_dispatch:
    inputs:
      core_ref:
        description: Use a specific version of the core for the workflow run. Defaults to master.
        default: ""
      wagon_dependency_ref:
        description: Use a specific version of the wagon dependency for the workflow run. Defaults to master.
        default: ""
      wagon_ref:
        description: Use a specific version of the wagon dependency for the workflow run. Defaults to master.
        default: "master"
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'VERSION'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'VERSION'

jobs:
  find-wagons:
    name: 'Find all Puzzle-managed wagons'
    runs-on: 'ubuntu-latest'
    outputs:
      wagons: ${{ steps.list-wagon-repositories.outputs.wagons }}

    steps:
      - name: 'List wagon repositories'
        id: list-wagon-repositories
        run: |
          WAGONS=$(gh repo list hitobito -L 100 --no-archived --json owner,name | \
            jq 'map(select(.name | test("^hitobito_"))) | map({ owner: .owner.login, repo: .name, name: .name | match("^hitobito_(.+)$").captures[0].string })')
          echo $WAGONS
          echo "wagons=$WAGONS" | tr -d "\n" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.WAGON_TESTS_GITHUB_TOKEN }}

  run-wagon-tests:
    name: 'Run ${{ matrix.wagon.name }} wagon tests'
    runs-on: 'ubuntu-latest'
    needs:
      - find-wagons
    strategy:
      fail-fast: false
      matrix:
        wagon: ${{ fromJSON(needs.find-wagons.outputs.wagons) }}
    steps:
      - name: Trigger ${{ matrix.wagon.name }} wagon tests
        uses: Codex-/return-dispatch@v2
        id: run-wagon-tests
        with:
          token: ${{ secrets.WAGON_TESTS_GITHUB_TOKEN }}
          repo: ${{ matrix.wagon.repo }}
          owner: ${{ matrix.wagon.owner }}
          ref: master
          workflow: tests.yml
          workflow_inputs: |
            {
              "core_ref": "${{ inputs.core_ref || github.ref || 'master' }}",
              "wagon_dependency_ref": "${{ inputs.wagon_dependency_ref || 'master' }}"
            }
      - name: Wait for ${{ matrix.wagon.name }} wagon tests result
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.WAGON_TESTS_GITHUB_TOKEN }}
          repo: ${{ matrix.wagon.repo }}
          owner: ${{ matrix.wagon.owner }}
          run_id: ${{ steps.run-wagon-tests.outputs.run_id }}
          run_timeout_seconds: 21600 # wait for up to 6 hours
          poll_interval_ms: 5000 # poll every 5 seconds
